#!/usr/bin/env bash
# tools/gen-template-provenance.sh — regenerate templates/PROVENANCE.sha1.
#
# WHY THIS EXISTS
#
# `sciagent activate` materializes a few template bodies into a project
# (.claude/hooks/*.sh, .claude/statusline.sh, 02_analysis/helpers/*.{py,R})
# with a plain `cp` — no
# placeholder substitution, so the file in the project is byte-identical to the
# template that produced it. Those bodies were written ONLY IF ABSENT, so a
# consumer provisioned once never received any later fix to a hook. Measured
# 2026-08-11: no_ephemeral.sh was stale in all 8 consumers that had it.
#
# The obvious fix — "refresh it if our .sciagent ownership record still matches"
# — is INERT on the real fleet: not one consumer has a record. The records were
# added long after those projects were provisioned. Absent record means, under
# the ownership discipline, "we did not write this, do not touch it".
#
# So provenance has to be re-established from the only evidence the consumer
# actually has: THE BYTES. If a file's content equals some version of the
# template that this toolkit has ever shipped, then the toolkit wrote it and
# nobody has edited it since — that is exactly the condition under which
# refreshing is safe. This script records those hashes.
#
# WHY A COMMITTED FILE RATHER THAN `git log` AT RUNTIME
#
# A release tarball / stripped install has no git history, and the consumer's
# submodule may be a shallow clone. Reading history at activate time would make
# the guarantee depend on how the toolkit was obtained. A committed manifest is
# the same in every install and costs one file read.
#
# KEEPING IT HONEST
#
# tests/test_template_provenance.sh fails if any managed template's CURRENT
# hash is missing from the manifest, so changing a template without re-running
# this script breaks the build rather than silently narrowing the set of
# copies the toolkit is willing to recognise as its own.
#
# Usage: tools/gen-template-provenance.sh [--check]
#   --check   exit 1 if the manifest is out of date; write nothing.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

MANIFEST="templates/PROVENANCE.sha1"

# The templates `activate` materializes verbatim. Keep in sync with
# claude_settings.sh's ensure_hooks / ensure_statusline and symlinks.sh's
# helper_shims_ensure. tests/test_template_provenance.sh derives the same set by
# globbing those three source dirs, so a template added to one of them and not
# added here fails the suite rather than shipping un-refreshable.
#
# README.md.template is deliberately absent: it carries a {{PROJECT_ID}}
# placeholder and belongs to `new project`'s substitution pass, so a rendered
# copy is NOT byte-equal to the template and content-provenance cannot apply.
#
# The 02_analysis/helpers shims are managed for the same reason the hooks are:
# `activate` materializes them with a plain `cp` (2026-08-12 — before that only
# `new project` ever wrote them), so the fleet is full of copies whose only
# evidence of authorship is their bytes. They carry no placeholder, so
# `new project`'s sed pass and `cp` produce identical output; the placeholder
# check in tests/test_template_provenance.sh is what keeps that true.
MANAGED=(
    "project/_common/.claude/hooks/no_ephemeral.sh.template"
    "project/_common/.claude/hooks/caption_sweep.sh.template"
    "project/_common/.claude/statusline.sh.template"
    "project/analysis/02_analysis/helpers/figure_style.py.template"
    "project/analysis/02_analysis/helpers/figure_style.R.template"
    "project/analysis/02_analysis/helpers/interactive_style.py.template"
)

_sha1() {
    if command -v sha1sum >/dev/null 2>&1; then sha1sum | cut -d' ' -f1
    else shasum -a 1 | cut -d' ' -f1
    fi
}

_generate() {
    cat <<'EOF'
# templates/PROVENANCE.sha1 — GENERATED by tools/gen-template-provenance.sh.
#
# Every content hash each managed template has EVER had, across git history
# plus the current working tree. `sciagent activate` uses this to decide
# whether a body already present in a project is an unmodified copy the
# toolkit wrote (-> safe to refresh) or something the user has edited
# (-> cede, never overwrite).
#
# Do not hand-edit. Regenerate with: tools/gen-template-provenance.sh
# Lines are: <sha1>  <path relative to templates/>
EOF
    local rel p sha seen
    for rel in "${MANAGED[@]}"; do
        p="templates/$rel"
        seen=""
        # Current working-tree version first, so a not-yet-committed template
        # is still recognised during development.
        if [[ -f "$p" ]]; then
            sha=$(_sha1 < "$p")
            printf '%s  %s\n' "$sha" "$rel"
            seen="$sha"
        fi
        # Then every historical version, oldest last (order is irrelevant to
        # the lookup; it is a set).
        local c hsha
        while read -r c; do
            [[ -n "$c" ]] || continue
            hsha=$(git show "$c:$p" 2>/dev/null | _sha1) || continue
            [[ -n "$hsha" ]] || continue
            case " $seen " in *" $hsha "*) continue ;; esac
            seen="$seen $hsha"
            printf '%s  %s\n' "$hsha" "$rel"
        done < <(git log --all --format=%H -- "$p" 2>/dev/null)
    done
}

if [[ "${1:-}" == "--check" ]]; then
    if [[ ! -f "$MANIFEST" ]]; then
        echo "gen-template-provenance: $MANIFEST is missing" >&2
        exit 1
    fi
    if ! diff -q <(_generate) "$MANIFEST" >/dev/null; then
        echo "gen-template-provenance: $MANIFEST is out of date" >&2
        echo "  run: tools/gen-template-provenance.sh" >&2
        exit 1
    fi
    exit 0
fi

_generate > "$MANIFEST"
echo "wrote: $MANIFEST ($(grep -cv '^#' "$MANIFEST") hashes)"
